name: â± Benchmarks
on:
  pull_request:
    types: [opened, synchronize, labeled]

jobs:
  benchmarks:
    if: contains(github.event.pull_request.labels.*.name, 'CI/Benchmarks')
    runs-on: ubuntu-latest
    env:
      DISPLAY: ':99.0'
    defaults:
      run:
        shell: bash
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y libasound2-dev libgl1-mesa-dev libxcursor-dev libxi-dev libxinerama-dev libxrandr-dev libxxf86vm-dev

      - name: Xvfb
        run: |
          Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

      - name: Checkout ${{ github.head_ref }}
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Setup benchstat
        run: |
          go get golang.org/x/perf/cmd/benchstat
          go install golang.org/x/perf/cmd/benchstat

      - name: Run benchmarks on ${{ github.head_ref }}
        id: benchmarks
        run: |
          go test -run='^$' -bench=. -count=10 test/benchmarks_test.go | grep -v "XGB:" > /tmp/benchmarks.txt
          echo "results<<EOF" >> "$GITHUB_OUTPUT"
          cat /tmp/benchmarks.txt >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"

      - name: Checkout master
        uses: actions/checkout@v4
        with:
          ref: 'master'

      - name: Run benchmarks on master
        id: benchmarks-master
        run: |
          go test -run='^$' -bench=. -count=10 test/benchmarks_test.go | grep -v "XGB:" > /tmp/benchmarks-master.txt
          echo "results<<EOF" >> "$GITHUB_OUTPUT"
          cat /tmp/benchmarks.txt >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"

      - name: Run benchmarks diff
        id: benchmarks-diff
        run: |
          benchstat /tmp/benchmarks-master.txt /tmp/benchmarks.txt > /tmp/benchmarks-diff.txt
          echo "results<<EOF" >> "$GITHUB_OUTPUT"
          cat /tmp/benchmarks-diff.txt >> "$GITHUB_OUTPUT"
          echo "EOF" >> "$GITHUB_OUTPUT"

      - name: Comment PR with benchmark results
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            ### Benchmarks
            
            <details>
              <summary>master VS ${{ github.head_ref }}</summary>

              ```
                ${{ steps.benchmarks-diff.outputs.results }}
              ```
            </details>
            
            <details>
              <summary>${{ github.head_ref }}</summary>

              ```
                ${{ steps.benchmarks.outputs.results }}
              ```
            </details>
            
            <details>
              <summary>master</summary>

              ```
                ${{ steps.benchmarks-master.outputs.results }}
              ```
            </details>
          comment_tag: benchmarks
